### ISSUE TITLE
AttributeError: 'Enzyme' object has no attribute 'definition'

### ISSUE THREAD

**Issue by AnaisBgd** [ryhaberecht/FEV-KEGG#3]
Hi,

I try to run a code similar to Experiment/02.py, but I received this error :
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\anais\Documents\code_metabo\metabopredict.py", line 1200, in <lambda>
    ok = Button(self, text='Ajouter', font=("Reem Kufi", 10), fg='green', command=lambda: self.ajout_especes())
  File "C:\Users\anais\Documents\code_metabo\metabopredict.py", line 1017, in ajout_especes
    str(enzyme.definition), str(enzyme.name), str(enzyme.getEcNumbersString()), product.__str__()))
AttributeError: 'Enzyme' object has no attribute 'definition'
```
It works if I write 'description' instead of 'definition', but in this case, it's only returns 'None'.

Can you help me ?
Thank you !

**Comment by ryhaberecht** [comment]
Great, you found your first bug! The _description_ attribute of the EcEnzyme object here was obviously mistaken with the _definition_ attribute of a Gene object.
Anyways, does experiment 2 output this for you?

> 9 results
C00037 -> b2903 gcvP [1.4.4.2] glycine decarboxylase -> C00011
C00065 -> b2585 pssA [2.7.8.8] phosphatidylserine synthase -> C02737
C00101 -> b2905 gcvT [2.1.2.10] aminomethyltransferase -> C00014
C00101 -> b2905 gcvT [2.1.2.10] aminomethyltransferase -> C02972
C01242 -> b2905 gcvT [2.1.2.10] aminomethyltransferase -> C00014
C01242 -> b2905 gcvT [2.1.2.10] aminomethyltransferase -> C02972
C02051 -> b2903 gcvP [1.4.4.2] glycine decarboxylase -> C00011
C02051 -> b2903 gcvP [1.4.4.2] glycine decarboxylase -> C01242
C02972 -> b0116 lpd [1.8.1.4] lipoamide dehydrogenase -> C02051

If yes, which other enzymes return _None_? It might be that they do not have a description in KEGG.

**Comment by AnaisBgd** [comment]
I just tested the code, and all enzymes return 'None' for the description.
```
9 results
C00037 -> b2903 (RefSeq) glycine decarboxylase [1.4.4.2] None -> C00011
C00065 -> b2585 (RefSeq) phosphatidylserine synthase [2.7.8.8] None -> C02737
C00101 -> b2905 (RefSeq) aminomethyltransferase [2.1.2.10] None -> C00014
C00101 -> b2905 (RefSeq) aminomethyltransferase [2.1.2.10] None -> C02972
C01242 -> b2905 (RefSeq) aminomethyltransferase [2.1.2.10] None -> C00014
C01242 -> b2905 (RefSeq) aminomethyltransferase [2.1.2.10] None -> C02972
C02051 -> b2903 (RefSeq) glycine decarboxylase [1.4.4.2] None -> C00011
C02051 -> b2903 (RefSeq) glycine decarboxylase [1.4.4.2] None -> C01242
C02972 -> b0116 (RefSeq) lipoamide dehydrogenase [1.8.1.4] None -> C02051
```
I had tried with other organisms the last week, like Pseudomonas aeruginosa, Mycoplasma pneumoniae or Faecalitalea cylindroides, I always have 'None' with all results, that's why I was suprise with that.

**Comment by ryhaberecht** [comment]
At first thought this was another regression in Python 3.9, but actually KEGG changed their gene data structure. Please do a `pip install -U FEV_KEGG` and try version 1.1.4.

PS: This version is incompatible with cached gene files of earlier versions, please remove all cache files created with version <= 1.1.3! See the readme for the cache folder location of your operating system.

**Comment by AnaisBgd** [comment]
It work now !
Thank you for your help !

**Comment by ryhaberecht** [comment]
Great! Have fun 🤙🏻
